config/routes.rb
Rails.application.routes.draw do
  root 'temas#index'
  # resources :temas
  resources :temas do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tema.rb
class Tema < ActiveRecord::Base
    has_many :votes, dependent: :destroy, foreign_key: :topic_id
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :tema , foreign_key: :topic_id
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]


  def upvote
    @temas = Tema.find(params[:id])
    @temas.votes.create
    redirect_to(temas_path)
  end

  def downvote
    @temas = Tema.find(params[:id])
    @temas.votes.first.destroy
    redirect_to(temas_path)
  end

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to temas_path, notice: 'Se a creado perfectamente.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to temas_path, notice: 'Se a Actualizado perfectamente.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy

    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:titulo, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suggestotron</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/temas/_form.html.erb
<%= form_with(model: tema, local: true) do |form| %>
  <% if tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tema.errors.count, "error") %> prohibited this tema from being saved:</h2>

      <ul>
      <% tema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :tema_titulo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :tema_descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/temas/edit.html.erb
<h1>Editing Tema</h1>

<%= render 'form', tema: @tema %>

<%= link_to 'Show', @tema %> |
<%= link_to 'Back', temas_path %>

app/views/temas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temas</h1>
<div>
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= link_to tema.titulo, tema %></td>
        <td><%= pluralize(tema.votes.count, "voto") %></td>
        <td class="boton"><%= button_to '+1', upvote_tema_path(tema), method: :post %></td>
        <td class="boton"><%= button_to '-1', downvote_tema_path(tema), method: :post %></td>
        <td><%= link_to 'Eliminar', tema, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tema', new_tema_path %>
</div>

app/views/temas/new.html.erb
<h1>New Tema</h1>

<%= render 'form', tema: @tema %>

<%= link_to 'Back', temas_path %>

app/views/temas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @tema.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tema.descripcion %>
</p>

<%= link_to 'Edit', edit_tema_path(@tema) %> |
<%= link_to 'Back', temas_path %>